spring:
  application:
    name: coinService

  data:
    mongodb:
      uri: mongodb://localhost:27017/coin-service

    redis:
      host: localhost
      port: 6379

server:
  port: 8081
  servlet:
    context-path: /coin



api-key:
  coingecko : CG-tH5kFFDaKPL

url : https://api.coingecko.com/api/v3/coins/