export const CHECK_FORMAT_IMAGE_REQUEST = "CHECK_FORMAT_IMAGE_REQUEST";
export const CHECK_FORMAT_IMAGE_SUCCESS = "CHECK_FORMAT_IMAGE_SUCCESS";
export const CHECK_FORMAT_IMAGE_FAILURE = "CHECK_FORMAT_IMAGE_FAILURE";

export const UPLOAD_FILE_TO_SERVER_REQUEST = "UPLOAD_FILE_TO_SERVER_REQUEST";
export const UPLOAD_FILE_TO_SERVER_SUCCESS = "UPLOAD_FILE_TO_SERVER_SUCCESS";
export const UPLOAD_FILE_TO_SERVER_FAILURE = "UPLOAD_FILE_TO_SERVER_FAILURE";
