export const GET_BALANCE_WALLET_REQUEST = "GET_BALANCE_WALLET_REQUEST";
export const GET_BALANCE_WALLET_SUCCESS = "GET_BALANCE_WALLET_SUCCESS";
export const GET_BALANCE_WALLET_FAILURE = "GET_BALANCE_WALLET_FAILURE";

export const GET_HISTORY_WALLET_FIAT_REQUEST =
  "GET_HISTORY_WALLET_FIAT_REQUEST";
export const GET_HISTORY_WALLET_FIAT_SUCCESS =
  "GET_HISTORY_WALLET_FIAT_SUCCESS";
export const GET_HISTORY_WALLET_FIAT_FAILURE =
  "GET_HISTORY_WALLET_FIAT_FAILURE";

export const GET_EXCHANGE_RATE_REQUEST = "GET_EXCHANGE_RATE_REQUEST";
export const GET_EXCHANGE_RATE_SUCCESS = "GET_EXCHANGE_RATE_SUCCESS";
export const GET_EXCHANGE_RATE_FAILURE = "GET_EXCHANGE_RATE_FAILURE";

export const UPDATE_WALLET_REQUEST = "UPDATE_WALLET_REQUEST";
export const UPDATE_WALLET_SUCCESS = "UPDATE_WALLET_SUCCESS";
export const UPDATE_WALLET_FAILURE = "UPDATE_WALLET_FAILURE";

export const SUBSTRACT_COIN_WALLET_REQUEST = "SUBSTRACT_COIN_WALLET_REQUEST";
export const SUBSTRACT_COIN_WALLET_SUCCESS = "SUBSTRACT_COIN_WALLET_SUCCESS";
export const SUBSTRACT_COIN_WALLET_FAILURE = "SUBSTRACT_COIN_WALLET_FAILURE";

export const ADD_COIN_WALLET_REQUEST = "ADD_COIN_WALLET_REQUEST";
export const ADD_COIN_WALLET_SUCCESS = "ADD_COIN_WALLET_SUCCESS";
export const ADD_COIN_WALLET_FAILURE = "ADD_COIN_WALLET_FAILURE";

export const UPDATE_WALLET_BUY_REQUEST = "UPDATE_WALLET_BUY_REQUEST";
export const UPDATE_WALLET_BUY_SUCCESS = "UPDATE_WALLET_BUY_SUCCESS";
export const UPDATE_WALLET_BUY_FAILURE = "UPDATE_WALLET_BUY_FAILURE";
