spring:
  application:
    name: identityService
  security:
    oath2:
      client:
        registration:
          google:
            client-id: 199551592608-nj0o32uicafdovcdbhst35fduqsn4j2u.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google

  datasource:
    url: jdbc:mysql://localhost:3306/crypt_user
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false


jwt:
  signerKey: Os1s6shIo1Cit3j+LWqRjlEjCu8wytD3tQFeIR6Opv1Qec+uafoNtUu1zWyvhVue
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

server:
  port: 8083
  servlet:
    context-path: /identity

app:
  services:
    profile: http://localhost:8084/profile

#Google Login
logging:
  level:
    org:
      springframework:
        security : TRACE


