export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGIN_TWO_STEP_REQUEST = "LOGIN_TWO_STEP_REQUEST";
export const LOGIN_TWO_STEP_SUCCESS = "LOGIN_TWO_STEP_SUCCESS";
export const LOGIN_TWO_STEP_FAILURE = "LOGIN_TWO_STEP_FAILURE";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const SEND_VERIFICATION_OTP_REQUEST = "SEND_VERIFICATION_OTP_REQUEST";
export const SEND_VERIFICATION_OTP_SUCCESS = "SEND_VERIFICATION_OTP_SUCCESS";
export const SEND_VERIFICATION_OTP_FAILURE = "SEND_VERIFICATION_OTP_FAILURE";

export const ENABLE_TWO_STEP_AUTHENTICATION_USER_REQUEST =
  "ENABLE_TWO_STEP_AUTHENTICATION_USER_REQUEST";
export const ENABLE_TWO_STEP_AUTHENTICATION_USER_SUCCESS =
  "ENABLE_TWO_STEP_AUTHENTICATION_USER_SUCCESS";
export const ENABLE_TWO_STEP_AUTHENTICATION_USER_FAILURE =
  "ENABLE_TWO_STEP_AUTHENTICATION_USER_FAILURE";

export const ENABLE_TWO_STEP_AUTHENTICATION_OAUTH_USER_REQUEST =
  "ENABLE_TWO_STEP_AUTHENTICATION_OAUTH_USER_REQUEST";
export const ENABLE_TWO_STEP_AUTHENTICATION_OAUTH_USER_SUCCESS =
  "ENABLE_TWO_STEP_AUTHENTICATION_OAUTH_USER_SUCCESS";
export const ENABLE_TWO_STEP_AUTHENTICATION_OAUTH_USER_FAILURE =
  "ENABLE_TWO_STEP_AUTHENTICATION_OAUTH_USER_FAILURE";

export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";

export const SEND_RESET_PASSWORD_REQUEST = "SEND_RESET_PASSWORD_REQUEST";
export const SEND_RESET_PASSWORD_SUCCESS = "SEND_RESET_PASSWORD_SUCCESS";
export const SEND_RESET_PASSWORD_FAILURE = "SEND_RESET_PASSWORD_FAILURE";

export const VERIFY_RESET_PASSWORD_REQUEST = "VERIFY_RESET_PASSWORD_REQUEST";
export const VERIFY_RESET_PASSWORD_SUCCESS = "VERIFY_RESET_PASSWORD_SUCCESS";
export const VERIFY_RESET_PASSWORD_FAILURE = "VERIFY_RESET_PASSWORD_FAILURE";

export const SEND_EMAIL_TWO_AUTH_REQUEST = "SEND_EMAIL_TWO_AUTH_REQUEST";
export const SEND_EMAIL_TWO_AUTH_SUCCESS = "SEND_EMAIL_TWO_AUTH_SUCCESS";
export const SEND_EMAIL_TWO_AUTH_FAILURE = "SEND_EMAIL_TWO_AUTH_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const CLEAR_ERROR = "CLEAR_ERROR";

export const CHECK_OTP_REQUEST = "CHECK_OTP_REQUEST";
export const CHECK_OTP_SUCCESS = "CHECK_OTP_SUCCESS";
export const CHECK_OTP_FAILURE = "CHECK_OTP_FAILURE";

export const SEND_EMAIL_REQUEST = "SEND_EMAIL_REQUEST";
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_FAILURE = "SEND_EMAIL_FAILURE";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILURE = "UPDATE_PASSWORD_FAILURE";

export const GET_EMAIL_REQUEST = "GET_EMAIL_REQUEST";
export const GET_EMAIL_SUCCESS = "GET_EMAIL_SUCCESS";
export const GET_EMAIL_FAILURE = "GET_EMAIL_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const SINGIN_GG_REQUEST = "SINGIN_GG_REQUEST";
export const SINGIN_GG_SUCCESS = "SINGIN_GG_SUCCESS";
export const SINGIN_GG_FAILURE = "SINGIN_GG_FAILURE";

export const CHANGE_PASSWORD_OLD_REQUEST = "CHANGE_PASSWORD_OLD_REQUEST";
export const CHANGE_PASSWORD_OLD_SUCCESS = "CHANGE_PASSWORD_OLD_SUCCESS";
export const CHANGE_PASSWORD_OLD_FAILURE = "CHANGE_PASSWORD_OLD_FAILURE";
