export const GET_ALL_ORDER_REQUEST = "GET_ALL_ORDER_REQUEST";
export const GET_ALL_ORDER_SUCCESS = "GET_ALL_ORDER_SUCCESS";
export const GET_ALL_ORDER_FAILURE = "GET_ALL_ORDER_FAILURE";

export const GET_ANOTHER_ORDER_REQUEST = "GET_ANOTHER_ORDER_REQUEST";
export const GET_ANOTHER_ORDER_SUCCESS = "GET_ANOTHER_ORDER_SUCCESS";
export const GET_ANOTHER_ORDER_FAILURE = "GET_ANOTHER_ORDER_FAILURE";

export const GET_PAGINATION_ORDER_REQUEST = "GET_PAGINATION_ORDER_REQUEST";
export const GET_PAGINATION_ORDER_SUCCESS = "GET_PAGINATION_ORDER_SUCCESS";
export const GET_PAGINATION_ORDER_FAILURE = "GET_PAGINATION_ORDER_FAILURE";

export const GET_ORDER_TYPE_COIN_REQUEST = "GET_ORDER_TYPE_COIN_REQUEST";
export const GET_ORDER_TYPE_COIN_SUCCESS = "GET_ORDER_TYPE_COIN_SUCCESS";
export const GET_ORDER_TYPE_COIN_FAILURE = "GET_ORDER_TYPE_COIN_FAILURE";

export const GET_ORDER_ANOTHER_TYPE_COIN_REQUEST =
  "GET_ORDER_ANOTHER_TYPE_COIN_REQUEST";
export const GET_ORDER_ANOTHER_TYPE_COIN_SUCCESS =
  "GET_ORDER_ANOTHER_TYPE_COIN_SUCCESS";
export const GET_ORDER_ANOTHER_TYPE_COIN_FAILURE =
  "GET_ORDER_ANOTHER_TYPE_COIN_FAILURE";

export const GET_ORDER_MY_TYPE_COIN_REQUEST = "GET_ORDER_MY_TYPE_COIN_REQUEST";
export const GET_ORDER_MY_TYPE_COIN_SUCCESS = "GET_ORDER_MY_TYPE_COIN_SUCCESS";
export const GET_ORDER_MY_TYPE_COIN_FAILURE = "GET_ORDER_MY_TYPE_COIN_FAILURE";

export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";

export const UPDATE_ORDER_BUY_REQUEST = "UPDATE_ORDER_BUY_REQUEST";
export const UPDATE_ORDER_BUY_SUCCESS = "UPDATE_ORDER_BUY_SUCCESS";
export const UPDATE_ORDER_BUY_FAILURE = "UPDATE_ORDER_BUY_FAILURE";

export const CREATE_BANK_REQUEST = "CREATE_BANK_REQUEST";
export const CREATE_BANK_SUCCESS = "CREATE_BANK_SUCCESS";
export const CREATE_BANK_FAILURE = "CREATE_BANK_FAILURE";

export const GET_BANK_REQUEST = "GET_BANK_REQUEST";
export const GET_BANK_SUCCESS = "GET_BANK_SUCCESS";
export const GET_BANK_FAILURE = "GET_BANK_FAILURE";

export const GET_PENDING_ORDER_REQUEST = "GET_PENDING_ORDER_REQUEST";
export const GET_PENDING_ORDER_SUCCESS = "GET_PENDING_ORDER_SUCCESS";
export const GET_PENDING_ORDER_FAILURE = "GET_PENDING_ORDER_FAILURE";

export const GET_HISTORY_ORDER_REQUEST = "GET_HISTORY_ORDER_REQUEST";
export const GET_HISTORY_ORDER_SUCCESS = "GET_HISTORY_ORDER_SUCCESS";
export const GET_HISTORY_ORDER_FAILURE = "GET_HISTORY_ORDER_FAILURE";

export const CANCEL_ORDER_REQUEST = "CANCEL_ORDER_REQUEST";
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const CANCEL_ORDER_FAILURE = "CANCEL_ORDER_FAILURE";
