export const SAVE_TRANSACTION_SWAP_COIN_REQUEST =
  "SAVE_TRANSACTION_SWAP_COIN_REQUEST";
export const SAVE_TRANSACTION_SWAP_COIN_SUCCESS =
  "SAVE_TRANSACTION_SWAP_COIN_SUCCESS";
export const SAVE_TRANSACTION_SWAP_COIN_FAILURE =
  "SAVE_TRANSACTION_SWAP_COIN_FAILURE";

export const GET_ALL_TRANSACTION_SWAP_COIN_REQUEST =
  "GET_ALL_TRANSACTION_SWAP_COIN_REQUEST";
export const GET_ALL_TRANSACTION_SWAP_COIN_SUCCESS =
  "GET_ALL_TRANSACTION_SWAP_COIN_SUCCESS";
export const GET_ALL_TRANSACTION_SWAP_COIN_FAILURE =
  "GET_ALL_TRANSACTION_SWAP_COIN_FAILURE";

export const CREATE_TRANSACTION_ORDER_LIMIT_REQUEST =
  "CREATE_TRANSACTION_ORDER_LIMIT_REQUEST";
export const CREATE_TRANSACTION_ORDER_LIMIT_SUCCESS =
  "CREATE_TRANSACTION_ORDER_LIMIT_SUCCESS";
export const CREATE_TRANSACTION_ORDER_LIMIT_FAILURE =
  "CREATE_TRANSACTION_ORDER_LIMIT_FAILURE";

export const UPDATE_TRANSACTION_ORDER_LIMIT_REQUEST =
  "UPDATE_TRANSACTION_ORDER_LIMIT_REQUEST";
export const UPDATE_TRANSACTION_ORDER_LIMIT_SUCCESS =
  "UPDATE_TRANSACTION_ORDER_LIMIT_SUCCESS";
export const UPDATE_TRANSACTION_ORDER_LIMIT_FAILURE =
  "UPDATE_TRANSACTION_ORDER_LIMIT_FAILURE";

export const GET_ALL_STATUS_PENDING_TRANSACTION_ORDER_LIMIT_REQUEST =
  "GET_ALL_STATUS_PENDING_TRANSACTION_ORDER_LIMIT_REQUEST";
export const GET_ALL_STATUS_PENDING_TRANSACTION_ORDER_LIMIT_SUCCESS =
  "GET_ALL_STATUS_PENDING_TRANSACTION_ORDER_LIMIT_SUCCESS";
export const GET_ALL_STATUS_PENDING_TRANSACTION_ORDER_LIMIT_FAILURE =
  "GET_ALL_STATUS_PENDING_TRANSACTION_ORDER_LIMIT_FAILURE";

export const GET_ALL_STATUS_ANOTHER_PENDING_TRANSACTION_ORDER_LIMIT_REQUEST =
  "GET_ALL_STATUS_ANOTHER_PENDING_TRANSACTION_ORDER_LIMIT_REQUEST";
export const GET_ALL_STATUS_ANOTHER_PENDING_TRANSACTION_ORDER_LIMIT_SUCCESS =
  "GET_ALL_STATUS_ANOTHER_PENDING_TRANSACTION_ORDER_LIMIT_SUCCESS";
export const GET_ALL_STATUS_ANOTHER_PENDING_TRANSACTION_ORDER_LIMIT_FAILURE =
  "GET_ALL_STATUS_ANOTHER_PENDING_TRANSACTION_ORDER_LIMIT_FAILURE";
