export const SAVE_TRANSACTION_SWAP_COIN_REQUEST =
  "SAVE_TRANSACTION_SWAP_COIN_REQUEST";
export const SAVE_TRANSACTION_SWAP_COIN_SUCCESS =
  "SAVE_TRANSACTION_SWAP_COIN_SUCCESS";
export const SAVE_TRANSACTION_SWAP_COIN_FAILURE =
  "SAVE_TRANSACTION_SWAP_COIN_FAILURE";

export const GET_ALL_TRANSACTION_SWAP_COIN_REQUEST =
  "GET_ALL_TRANSACTION_SWAP_COIN_REQUEST";
export const GET_ALL_TRANSACTION_SWAP_COIN_SUCCESS =
  "GET_ALL_TRANSACTION_SWAP_COIN_SUCCESS";
export const GET_ALL_TRANSACTION_SWAP_COIN_FAILURE =
  "GET_ALL_TRANSACTION_SWAP_COIN_FAILURE";
