export const GET_USER_WATCH_LIST_REQUEST = "GET_USER_WATCH_LIST_REQUEST";
export const GET_USER_WATCH_LIST_SUCCESS = "GET_USER_WATCH_LIST_SUCCESS";
export const GET_USER_WATCH_LIST_FAILURE = "GET_USER_WATCH_LIST_FAILURE";

export const ADD_COIN_TO_WATCH_LIST_REQUEST = "ADD_COIN_TO_WATCH_LIST_REQUEST";
export const ADD_COIN_TO_WATCH_LIST_SUCCESS = "ADD_COIN_TO_WATCH_LIST_SUCCESS";
export const ADD_COIN_TO_WATCH_LIST_FAILURE = "ADD_COIN_TO_WATCH_LIST_FAILURE";
