export const GET_USER_WATCH_LIST_REQUEST = "GET_USER_WATCH_LIST_REQUEST";
export const GET_USER_WATCH_LIST_SUCCESS = "GET_USER_WATCH_LIST_SUCCESS";
export const GET_USER_WATCH_LIST_FAILURE = "GET_USER_WATCH_LIST_FAILURE";

export const TOGGLE_COIN_TO_WATCH_LIST_REQUEST =
  "TOGGLE_COIN_TO_WATCH_LIST_REQUEST";
export const TOGGLE_COIN_TO_WATCH_LIST_SUCCESS =
  "TOGGLE_COIN_TO_WATCH_LIST_SUCCESS";
export const TOGGLE_COIN_TO_WATCH_LIST_FAILURE =
  "TOGGLE_COIN_TO_WATCH_LIST_FAILURE";
