export const GET_NOTIFY_USER_REQUEST = "GET_NOTIFY_USER_REQUEST";
export const GET_NOTIFY_USER_SUCCESS = "GET_NOTIFY_USER_SUCCESS";
export const GET_NOTIFY_USER_FAILURE = "GET_NOTIFY_USER_FAILURE";

export const PUT_NOTIFY_CONVERT_READ_USER_REQUEST =
  "PUT_NOTIFY_CONVERT_READ_USER_REQUEST";
export const PUT_NOTIFY_CONVERT_READ_USER_SUCCESS =
  "PUT_NOTIFY_CONVERT_READ_USER_SUCCESS";
export const PUT_NOTIFY_CONVERT_READ_USER_FAILURE =
  "PUT_NOTIFY_CONVERT_READ_USER_FAILURE";

export const PUT_NOTIFY__CONVERT_HANDLE_REQUEST =
  "PUT_NOTIFY__CONVERT_HANDLE_REQUEST";
export const PUT_NOTIFY__CONVERT_HANDLE_SUCCESS =
  "PUT_NOTIFY__CONVERT_HANDLE_SUCCESS";
export const PUT_NOTIFY__CONVERT_HANDLE_FAILURE =
  "PUT_NOTIFY__CONVERT_HANDLE_FAILURE";

export const DELETE_NOTIFY_REQUEST = "DELETE_NOTIFY_REQUEST";
export const DELETE_NOTIFY_SUCCESS = "DELETE_NOTIFY_SUCCESS";
export const DELETE_NOTIFY_FAILURE = "DELETE_NOTIFY_FAILURE";

export const DELETE_NOTIFY_READ_HANDLED_REQUEST =
  "DELETE_NOTIFY_READ_HANDLED_REQUEST";
export const DELETE_NOTIFY_READ_HANDLED_SUCCESS =
  "DELETE_NOTIFY_READ_HANDLED_SUCCESS";
export const DELETE_NOTIFY_READ_HANDLED_FAILURE =
  "DELETE_NOTIFY_READ_HANDLED_FAILURE";
