export const FETCH_COIN_LIST_REQUEST = "FETCH_COIN_LIST_REQUEST";
export const FETCH_COIN_LIST_SUCCESS = "FETCH_COIN_LIST_SUCCESS";
export const FETCH_COIN_LIST_FAILURE = "FETCH_COIN_LIST_FAILURE";

export const FETCH_ALL_COIN_REQUEST = "FETCH_ALL_COIN_REQUEST";
export const FETCH_ALL_COIN_SUCCESS = "FETCH_ALL_COIN_SUCCESS";
export const FETCH_ALL_COIN_FAILURE = "FETCH_ALL_COIN_FAILURE";

export const FETCH_TOP50_COINS_REQUEST = "FETCH_TOP50_COINS_REQUEST";
export const FETCH_TOP50_COINS_SUCCESS = "FETCH_TOP50_COINS_SUCCESS";
export const FETCH_TOP50_COINS_FAILURE = "FETCH_TOP50_COINS_FAILURE";

export const FETCH_TOPGAINERS_COINS_REQUEST = "FETCH_TOPGAINERS_COINS_REQUEST";
export const FETCH_TOPGAINERS_COINS_SUCCESS = "FETCH_TOPGAINERS_COINS_SUCCESS";
export const FETCH_TOPGAINERS_COINS_FAILURE = "FETCH_TOPGAINERS_COINS_FAILURE";

export const FETCH_TOPLOSERS_COINS_REQUEST = "FETCH_TOPLOSERS_COINS_REQUEST";
export const FETCH_TOPLOSERS_COINS_SUCCESS = "FETCH_TOPLOSERS_COINS_SUCCESS";
export const FETCH_TOPLOSERS_COINS_FAILURE = "FETCH_TOPLOSERS_COINS_FAILURE";

export const FETCH_MARKET_CHART_REQUEST = "FETCH_MARKET_CHART_REQUEST";
export const FETCH_MARKET_CHART_SUCCESS = "FETCH_MARKET_CHART_SUCCESS";
export const FETCH_MARKET_CHART_FAILURE = "FETCH_COIN_LIST_FAILURE";

export const FETCH_COIN_BY_ID_REQUEST = "FETCH_COIN_BY_ID_REQUEST";
export const FETCH_COIN_BY_ID_SUCCESS = "FETCH_COIN_BY_ID_SUCCESS";
export const FETCH_COIN_BY_ID_FAILURE = "FETCH_COIN_BY_ID_FAILURE";

export const FETCH_COIN_DETAILS_REQUEST = "FETCH_COIN_DETAILS_REQUEST";
export const FETCH_COIN_DETAILS_SUCCESS = "FETCH_COIN_DETAILS_SUCCESS";
export const FETCH_COIN_DETAILS_FAILURE = "FETCH_COIN_DETAILS_FAILURE";

export const RESET_COIN_DETAILS_REQUEST = "RESET_COIN_DETAILS_REQUEST";
export const RESET_COIN_DETAILS_SUCCESS = "RESET_COIN_DETAILS_SUCCESS";
export const RESET_COIN_DETAILS_FAILURE = "RESET_COIN_DETAILS_FAILURE";

export const SEARCH_COIN_REQUEST = "SEARCH_COIN_REQUEST";
export const SEARCH_COIN_SUCCESS = "SEARCH_COIN_SUCCESS";
export const SEARCH_COIN_FAILURE = "SEARCH_COIN_FAILURE";
